<?= $this->extend('layouts/app') ?>

<?= $this->section('content') ?>
<div class="content">
    <div class="page-header">
        <div class="add-item d-flex">
            <div class="page-title">
                <h4 class="fw-bold">AI Career Advice</h4>
                <h6>Personalized guidance for your career journey.</h6>
            </div>
        </div>
        <div class="page-btn">
            <a href="<?= base_url('candidate/career-tools') ?>" class="btn btn-secondary btn-sm">
                <i class="ti ti-arrow-left me-1"></i> Back to Tools
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-xl-9 mx-auto">
            <div class="card custom-card border-0 shadow-sm">
                <div class="card-header bg-info py-3">
                    <div class="d-flex align-items-center">
                        <div class="avatar avatar-md bg-white-transparent me-3">
                            <i class="ti ti-sparkles text-white fs-20"></i>
                        </div>
                        <div>
                            <h6 class="text-white fw-bold mb-0">Personalized Career Coaching</h6>
                            <p class="text-white-50 fs-12 mb-0">Based on your current profile and skills</p>
                        </div>
                    </div>
                </div>
                <div class="card-body p-5">
                    <div class="advice-content fs-15 text-muted line-height-lg">
                        <?= nl2br($advice) ?>
                    </div>
                </div>
                <div class="card-footer border-top bg-light p-4">
                    <div class="d-flex align-items-center justify-content-between">
                        <p class="mb-0 fs-13 text-muted">Advice generated by JobberRecruit AI Career Coach.</p>
                        <button class="btn btn-outline-info btn-sm" onclick="window.print()">
                            <i class="ti ti-printer me-1"></i> Print Advice
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.advice-content h1, .advice-content h2, .advice-content h3 {
    color: #0dcaf0;
    margin-top: 1.5rem;
    margin-bottom: 1rem;
    font-weight: 700;
}
.advice-content p {
    margin-bottom: 1.2rem;
}
.advice-content ul {
    margin-bottom: 1.5rem;
}
.advice-content li {
    margin-bottom: 0.5rem;
}
.line-height-lg {
    line-height: 1.8;
}
</style>
<?= $this->endSection() ?>
