<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class JobSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'title' => 'Senior Non-Key Expert - ICT / Software Specialist',
                'description' => '<p>Responsible for reviewing and improving election-related ICT systems, training protocols, and monitoring deployment activities in Nigeria.</p>',
                'job_type' => 'full-time',
                'employer_id' => 1,
                'state_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦750,000 - ₦1,200,000',
                'industry_id' => 2,
                'category_id' => 1,
                'education_level' => 'master',
                'experience_level' => 'senior',
                'skills' => 'PHP, JavaScript, SQL, Laravel, DevOps',
                'requirements' => '<ul><li>10+ years of experience in software engineering</li><li>Strong background in ICT systems</li></ul>',
                'application_deadline' => '2025-11-01',
                'start_date' => '2025-11-15',
                'contact_email' => 'hr@bitride.ng',
                'contact_phone' => '+2348149983395',
                'application' => 'Submit your CV and cover letter via email.',
            ],
            [
                'title' => 'Frontend Developer (React)',
                'description' => '<p>We are looking for a talented frontend developer to build intuitive web applications with React and Tailwind CSS.</p>',
                'job_type' => 'part-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'hybrid',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦300,000 - ₦500,000',
                'industry_id' => 3,
                'category_id' => 2,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'React, JavaScript, TailwindCSS, Git',
                'requirements' => '<ul><li>2+ years of experience with React</li><li>Good eye for UI/UX</li></ul>',
                'application_deadline' => '2025-10-20',
                'start_date' => '2025-11-01',
                'contact_email' => 'jobs@bitride.ng',
                'contact_phone' => '08149983395',
                'application' => 'Apply via our careers page.',
            ],
            [
                'title' => 'Mobile App Developer (Flutter)',
                'description' => '<p>Join our growing mobile engineering team to develop cross-platform apps for food delivery and logistics services.</p>',
                'job_type' => 'contract',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'fixed',
                'salary_period' => 'monthly',
                'salary' => '₦400,000',
                'industry_id' => 4,
                'category_id' => 3,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Flutter, Dart, REST APIs, Firebase',
                'requirements' => '<ul><li>3+ years Flutter experience</li><li>Published at least 2 apps</li></ul>',
                'application_deadline' => '2025-10-25',
                'start_date' => '2025-11-10',
                'contact_email' => 'recruit@bitride.ng',
                'contact_phone' => '08150000000',
                'application' => 'Attach your GitHub portfolio.',
            ],
            [
                'title' => 'Data Analyst',
                'description' => '<p>Analyze business and product data to generate insights and performance dashboards.</p>',
                'job_type' => 'freelance',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦200,000 - ₦350,000',
                'industry_id' => 5,
                'category_id' => 4,
                'education_level' => 'bachelor',
                'experience_level' => 'entry',
                'skills' => 'SQL, Excel, PowerBI, Python',
                'requirements' => '<ul><li>1+ year data experience</li><li>Good communication skills</li></ul>',
                'application_deadline' => '2025-10-30',
                'start_date' => '2025-11-05',
                'contact_email' => 'data@bitride.ng',
                'contact_phone' => '+2347012345678',
                'application' => 'Send sample reports and resume.',
            ],
            [
                'title' => 'Rider Operations Associate',
                'description' => '<p>Coordinate rider onboarding, manage route allocation, and monitor performance metrics for the delivery platform.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'on-site',
                'salary_type' => 'negotiable',
                'salary_period' => 'monthly',
                'salary' => '',
                'industry_id' => 6,
                'category_id' => 5,
                'education_level' => 'high-school',
                'experience_level' => 'entry',
                'skills' => 'Excel, Communication, Organization',
                'requirements' => '<ul><li>Knowledge of local areas</li><li>Good people management</li></ul>',
                'application_deadline' => '2025-11-10',
                'start_date' => '2025-11-15',
                'contact_email' => 'ops@bitride.ng',
                'contact_phone' => '+2348020000000',
                'application' => 'Walk-in interviews are allowed weekdays 9am–4pm.',
            ],
            [
                'title' => 'Backend Engineer (Node.js)',
                'description' => '<p>Develop scalable backend services and APIs for our logistics platform using Node.js and MongoDB.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'hybrid',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦450,000 - ₦700,000',
                'industry_id' => 7,
                'category_id' => 6,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Node.js, MongoDB, Express, AWS',
                'requirements' => '<ul><li>3+ years backend development</li><li>Experience with cloud services</li></ul>',
                'application_deadline' => '2025-11-05',
                'start_date' => '2025-11-20',
                'contact_email' => 'engineering@bitride.ng',
                'contact_phone' => '+2348030000000',
                'application' => 'Submit code samples or GitHub profile.',
            ],
            [
                'title' => 'UX/UI Designer',
                'description' => '<p>Create user-centered designs for web and mobile applications, focusing on usability and accessibility.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦350,000 - ₦550,000',
                'industry_id' => 8,
                'category_id' => 7,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Figma, Adobe XD, Prototyping, User Research',
                'requirements' => '<ul><li>4+ years UX/UI design experience</li><li>Strong portfolio required</li></ul>',
                'application_deadline' => '2025-10-28',
                'start_date' => '2025-11-08',
                'contact_email' => 'design@bitride.ng',
                'contact_phone' => '+2348040000000',
                'application' => 'Submit portfolio link with application.',
            ],
            [
                'title' => 'DevOps Engineer',
                'description' => '<p>Manage cloud infrastructure, implement CI/CD pipelines, and ensure system reliability and scalability.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦600,000 - ₦900,000',
                'industry_id' => 9,
                'category_id' => 8,
                'education_level' => 'bachelor',
                'experience_level' => 'senior',
                'skills' => 'AWS, Docker, Kubernetes, Jenkins, Terraform',
                'requirements' => '<ul><li>5+ years DevOps experience</li><li>Strong knowledge of cloud infrastructure</li></ul>',
                'application_deadline' => '2025-11-12',
                'start_date' => '2025-11-25',
                'contact_email' => 'devops@bitride.ng',
                'contact_phone' => '+2348050000000',
                'application' => 'Technical assessment required.',
            ],
            [
                'title' => 'Customer Support Representative',
                'description' => '<p>Provide excellent customer service, handle inquiries, and resolve issues for our platform users.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'on-site',
                'salary_type' => 'fixed',
                'salary_period' => 'monthly',
                'salary' => '₦150,000',
                'industry_id' => 10,
                'category_id' => 9,
                'education_level' => 'diploma',
                'experience_level' => 'entry',
                'skills' => 'Communication, Problem Solving, CRM',
                'requirements' => '<ul><li>1+ year customer service experience</li><li>Excellent communication skills</li></ul>',
                'application_deadline' => '2025-10-22',
                'start_date' => '2025-11-01',
                'contact_email' => 'support@bitride.ng',
                'contact_phone' => '+2348060000000',
                'application' => 'Send CV and cover letter.',
            ],
            [
                'title' => 'Digital Marketing Specialist',
                'description' => '<p>Develop and execute digital marketing campaigns across various channels to drive user acquisition.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'hybrid',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦250,000 - ₦400,000',
                'industry_id' => 11,
                'category_id' => 10,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'SEO, Social Media, Google Ads, Analytics',
                'requirements' => '<ul><li>3+ years digital marketing experience</li><li>Proven track record of successful campaigns</li></ul>',
                'application_deadline' => '2025-11-08',
                'start_date' => '2025-11-18',
                'contact_email' => 'marketing@bitride.ng',
                'contact_phone' => '+2348070000000',
                'application' => 'Include portfolio of previous campaigns.',
            ],
            [
                'title' => 'Product Manager',
                'description' => '<p>Lead product development from conception to launch, working with cross-functional teams to deliver value.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'hybrid',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦800,000 - ₦1,500,000',
                'industry_id' => 12,
                'category_id' => 11,
                'education_level' => 'master',
                'experience_level' => 'senior',
                'skills' => 'Product Strategy, Agile, User Research, Roadmapping',
                'requirements' => '<ul><li>7+ years product management experience</li><li>Technical background preferred</li></ul>',
                'application_deadline' => '2025-11-15',
                'start_date' => '2025-12-01',
                'contact_email' => 'products@bitride.ng',
                'contact_phone' => '+2348080000000',
                'application' => 'Submit product case studies.',
            ],
            [
                'title' => 'Quality Assurance Engineer',
                'description' => '<p>Design and execute test plans, automate testing processes, and ensure product quality standards.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦300,000 - ₦500,000',
                'industry_id' => 13,
                'category_id' => 12,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Selenium, Jest, Cypress, Test Planning',
                'requirements' => '<ul><li>4+ years QA experience</li><li>Strong automation skills</li></ul>',
                'application_deadline' => '2025-10-30',
                'start_date' => '2025-11-12',
                'contact_email' => 'qa@bitride.ng',
                'contact_phone' => '+2348090000000',
                'application' => 'Include testing portfolio.',
            ],
            [
                'title' => 'Business Development Executive',
                'description' => '<p>Identify new business opportunities, build partnerships, and drive revenue growth for the company.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'on-site',
                'salary_type' => 'commission',
                'salary_period' => 'monthly',
                'salary' => '₦200,000 + Commission',
                'industry_id' => 14,
                'category_id' => 13,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Sales, Negotiation, Relationship Building',
                'requirements' => '<ul><li>3+ years B2B sales experience</li><li>Proven track record in business development</li></ul>',
                'application_deadline' => '2025-11-05',
                'start_date' => '2025-11-15',
                'contact_email' => 'bizdev@bitride.ng',
                'contact_phone' => '+2348100000000',
                'application' => 'Submit sales achievement records.',
            ],
            [
                'title' => 'Content Writer',
                'description' => '<p>Create engaging content for blogs, social media, and marketing materials to build brand awareness.</p>',
                'job_type' => 'part-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'fixed',
                'salary_period' => 'monthly',
                'salary' => '₦180,000',
                'industry_id' => 15,
                'category_id' => 14,
                'education_level' => 'bachelor',
                'experience_level' => 'entry',
                'skills' => 'Writing, SEO, Research, Creativity',
                'requirements' => '<ul><li>2+ years content writing experience</li><li>Portfolio of published work</li></ul>',
                'application_deadline' => '2025-10-25',
                'start_date' => '2025-11-05',
                'contact_email' => 'content@bitride.ng',
                'contact_phone' => '+2348110000000',
                'application' => 'Submit writing samples.',
            ],
            [
                'title' => 'System Administrator',
                'description' => '<p>Maintain and optimize IT infrastructure, ensure system security, and provide technical support.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'on-site',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦400,000 - ₦600,000',
                'industry_id' => 16,
                'category_id' => 15,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Linux, Windows Server, Networking, Security',
                'requirements' => '<ul><li>5+ years system administration</li><li>Relevant certifications preferred</li></ul>',
                'application_deadline' => '2025-11-10',
                'start_date' => '2025-11-22',
                'contact_email' => 'sysadmin@bitride.ng',
                'contact_phone' => '+2348120000000',
                'application' => 'Technical interview required.',
            ],
            [
                'title' => 'HR Business Partner',
                'description' => '<p>Support talent management, employee relations, and organizational development initiatives.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'hybrid',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦450,000 - ₦650,000',
                'industry_id' => 17,
                'category_id' => 16,
                'education_level' => 'bachelor',
                'experience_level' => 'senior',
                'skills' => 'Recruitment, Employee Relations, HR Policies',
                'requirements' => '<ul><li>6+ years HR experience</li><li>Knowledge of labor laws</li></ul>',
                'application_deadline' => '2025-11-12',
                'start_date' => '2025-11-26',
                'contact_email' => 'hr@bitride.ng',
                'contact_phone' => '+2348130000000',
                'application' => 'Submit detailed CV with HR achievements.',
            ],
            [
                'title' => 'Financial Analyst',
                'description' => '<p>Analyze financial data, prepare reports, and provide insights to support business decisions.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'on-site',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦500,000 - ₦750,000',
                'industry_id' => 18,
                'category_id' => 17,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Financial Modeling, Excel, Analysis, Reporting',
                'requirements' => '<ul><li>4+ years financial analysis</li><li>Accounting background preferred</li></ul>',
                'application_deadline' => '2025-11-08',
                'start_date' => '2025-11-20',
                'contact_email' => 'finance@bitride.ng',
                'contact_phone' => '+2348140000000',
                'application' => 'Submit analysis samples.',
            ],
            [
                'title' => 'Cybersecurity Specialist',
                'description' => '<p>Protect company systems and data from security threats, implement security protocols.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦700,000 - ₦1,100,000',
                'industry_id' => 19,
                'category_id' => 18,
                'education_level' => 'bachelor',
                'experience_level' => 'senior',
                'skills' => 'Security, Penetration Testing, Risk Assessment',
                'requirements' => '<ul><li>5+ years cybersecurity experience</li><li>Relevant certifications required</li></ul>',
                'application_deadline' => '2025-11-18',
                'start_date' => '2025-12-02',
                'contact_email' => 'security@bitride.ng',
                'contact_phone' => '+2348150000000',
                'application' => 'Security clearance check required.',
            ],
            [
                'title' => 'Project Coordinator',
                'description' => '<p>Coordinate project activities, track progress, and ensure timely delivery of project milestones.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'hybrid',
                'salary_type' => 'fixed',
                'salary_period' => 'monthly',
                'salary' => '₦350,000',
                'industry_id' => 20,
                'category_id' => 19,
                'education_level' => 'bachelor',
                'experience_level' => 'entry',
                'skills' => 'Project Management, Communication, Organization',
                'requirements' => '<ul><li>2+ years project coordination</li><li>PMP certification a plus</li></ul>',
                'application_deadline' => '2025-10-29',
                'start_date' => '2025-11-10',
                'contact_email' => 'projects@bitride.ng',
                'contact_phone' => '+2348160000000',
                'application' => 'Submit project management examples.',
            ],
            [
                'title' => 'AI/Machine Learning Engineer',
                'description' => '<p>Develop machine learning models and AI solutions to enhance platform intelligence and automation.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦900,000 - ₦1,400,000',
                'industry_id' => 21,
                'category_id' => 20,
                'education_level' => 'master',
                'experience_level' => 'senior',
                'skills' => 'Python, TensorFlow, PyTorch, ML Algorithms',
                'requirements' => '<ul><li>5+ years ML engineering</li><li>Strong mathematical background</li></ul>',
                'application_deadline' => '2025-11-20',
                'start_date' => '2025-12-05',
                'contact_email' => 'ai@bitride.ng',
                'contact_phone' => '+2348170000000',
                'application' => 'Submit research papers or project portfolio.',
            ],
            [
                'title' => 'Sales Manager',
                'description' => '<p>Lead sales team, develop sales strategies, and drive revenue growth across multiple channels.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'on-site',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦600,000 - ₦900,000 + Bonus',
                'industry_id' => 22,
                'category_id' => 13,
                'education_level' => 'bachelor',
                'experience_level' => 'senior',
                'skills' => 'Sales Management, Team Leadership, Strategy',
                'requirements' => '<ul><li>8+ years sales experience</li><li>3+ years in management role</li></ul>',
                'application_deadline' => '2025-11-14',
                'start_date' => '2025-11-28',
                'contact_email' => 'sales@bitride.ng',
                'contact_phone' => '+2348180000000',
                'application' => 'Submit sales team performance records.',
            ],
            [
                'title' => 'Technical Writer',
                'description' => '<p>Create comprehensive documentation for APIs, user guides, and technical specifications.</p>',
                'job_type' => 'contract',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'fixed',
                'salary_period' => 'monthly',
                'salary' => '₦320,000',
                'industry_id' => 23,
                'category_id' => 14,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Technical Writing, Documentation, API Docs',
                'requirements' => '<ul><li>3+ years technical writing</li><li>Experience with developer documentation</li></ul>',
                'application_deadline' => '2025-11-03',
                'start_date' => '2025-11-15',
                'contact_email' => 'docs@bitride.ng',
                'contact_phone' => '+2348190000000',
                'application' => 'Submit writing samples and portfolio.',
            ],
            [
                'title' => 'Database Administrator',
                'description' => '<p>Manage database systems, optimize performance, and ensure data integrity and security.</p>',
                'job_type' => 'full-time',
                'state_id' => 1,
                'employer_id' => 1,
                'location_type' => 'hybrid',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦550,000 - ₦800,000',
                'industry_id' => 24,
                'category_id' => 8,
                'education_level' => 'bachelor',
                'experience_level' => 'senior',
                'skills' => 'MySQL, PostgreSQL, MongoDB, Performance Tuning',
                'requirements' => '<ul><li>6+ years DBA experience</li><li>Strong knowledge of database optimization</li></ul>',
                'application_deadline' => '2025-11-16',
                'start_date' => '2025-11-30',
                'contact_email' => 'dba@bitride.ng',
                'contact_phone' => '+2348200000000',
                'application' => 'Technical assessment required.',
            ],
            [
                'title' => 'Social Media Manager',
                'description' => '<p>Develop and implement social media strategy to increase brand presence and engagement.</p>',
                'job_type' => 'full-time',
                'state_id' => 2,
                'employer_id' => 1,
                'location_type' => 'remote',
                'salary_type' => 'range',
                'salary_period' => 'monthly',
                'salary' => '₦280,000 - ₦420,000',
                'industry_id' => 25,
                'category_id' => 10,
                'education_level' => 'bachelor',
                'experience_level' => 'mid',
                'skills' => 'Social Media, Content Creation, Analytics',
                'requirements' => '<ul><li>4+ years social media management</li><li>Proven growth track record</li></ul>',
                'application_deadline' => '2025-11-07',
                'start_date' => '2025-11-18',
                'contact_email' => 'social@bitride.ng',
                'contact_phone' => '+2348210000000',
                'application' => 'Submit social media portfolio.',
            ]
        ];

        // Insert multiple records using the model to trigger hooks (like slug generation)
        $jobModel = model('JobModel');
        foreach ($data as $job) {
            $jobModel->insert($job);
        }
    }
}
