<?= $this->extend('layouts/app') ?>

<?= $this->section('styles') ?>
<link rel="stylesheet" href="<?= base_url('css/candidate-profile.css') ?>">
<style>
.advice-content {
    line-height: 1.8;
}
.advice-content h1, .advice-content h2, .advice-content h3 {
    color: var(--brand-deep);
    font-family: 'Sora', sans-serif;
    margin-top: 1.5rem;
    margin-bottom: 1rem;
    font-weight: 800;
}
.advice-content h1 { font-size: 1.5rem; }
.advice-content h2 { font-size: 1.3rem; }
.advice-content h3 { font-size: 1.15rem; }
.advice-content p { margin-bottom: 1.2rem; font-size: 0.86rem; color: var(--text); }
.advice-content ul, .advice-content ol { margin-bottom: 1.5rem; padding-left: 1.5rem; }
.advice-content li { margin-bottom: 0.5rem; font-size: 0.84rem; }
.advice-content strong { color: var(--brand-deep); font-weight: 700; }
</style>
<?= $this->endSection() ?>

<?= $this->section('content') ?>
<div class="content">
    
    <!-- Hero -->
    <section class="coach-hero" aria-labelledby="studio-title" style="margin-bottom: 24px; border-radius: var(--radius-lg); color: #fff; padding: 34px; background: radial-gradient(ellipse 60% 90% at 88% 8%,rgba(237,144,32,.22) 0%,transparent 55%),linear-gradient(150deg,#0A2F57 0%,#064A85 55%,#0861A9 100%);">
        <div class="hero-grid" style="display: grid; grid-template-columns: 1fr auto; gap: 20px; align-items: center;">
            <div>
                <div class="hero-badges" style="display: flex; gap: 8px; margin-bottom: 12px;">
                    <span class="hb hb--premium" style="background: rgba(237,144,32,.18); border: 1px solid rgba(237,144,32,.45); color: #ffd9a8; font-size: 0.66rem; font-weight: 700; padding: 5px 12px; border-radius: 20px;">
                        <svg aria-hidden="true" style="width:12px;height:12px;display:inline-block;vertical-align:middle;margin-right:4px;fill:currentColor;"><use href="#i-crown"/></svg> Premium Advice
                    </span>
                </div>
                <h1 id="studio-title" style="font-family:'Sora',sans-serif; font-size:clamp(1.5rem,3.4vw,2.15rem); font-weight:800; color:#fff; margin:0 0 8px;">AI Career Coach</h1>
                <p class="hero-sub" style="font-size:0.92rem; color:rgba(255,255,255,0.85); line-height:1.6; max-width:560px;">Tailored professional insights and strategic roadmap based on your current profile.</p>
            </div>
            <div class="page-actions" style="margin-top: 10px;">
                <a href="<?= base_url('candidate/career-tools') ?>" class="btn btn-ghost-w btn-sm">
                    <svg aria-hidden="true" style="width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:2;"><use href="#i-arrow-l"/></svg> Back to Tools
                </a>
            </div>
        </div>
    </section>

    <!-- Advice Card -->
    <div style="max-width: 800px; margin: 0 auto;">
        <section class="card" aria-label="Career Coach advice content" style="padding: 32px;">
            <div class="advice-content">
                <?= $advice /* HTML built by CareerToolsController::cleanMarkdown(), which escapes raw input before adding formatting tags */ ?>
            </div>

            <div style="border-top: 1px solid var(--border); margin-top: 30px; padding-top: 20px; display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px;">
                <p style="font-size: 0.76rem; color: var(--muted); margin: 0;">Generated by JobberRecruit AI Career Coach.</p>
                <button class="btn btn-outline btn-sm" onclick="window.print()">
                    Print Advice
                </button>
            </div>
        </section>
    </div>
</div>
<?= $this->endSection() ?>

