<?php

namespace App\Controllers;

use App\Models\CampaignStatModel;
use App\Models\EmailLogModel;
use App\Models\NewsletterModel;

class NewsletterAnalyticsController extends BaseController
{
    public function index($campaign_id = null)
    {
        if (!$campaign_id) {
            return redirect()->to('/admin/newsletters')->with('error', 'Campaign ID is required for analytics.');
        }

        $newsletterModel = new NewsletterModel();
        $campaign = $newsletterModel->find($campaign_id);

        if (!$campaign) {
            return redirect()->to('/admin/newsletters')->with('error', 'Campaign not found.');
        }

        $statModel = new CampaignStatModel();
        $logModel = new EmailLogModel();

        $stats = $statModel->where('campaign_id', $campaign_id)->first();
        
        // If stats are not yet generated by the cron job, we can create a dummy structure
        if (!$stats) {
            $stats = (object)[
                'total_recipients' => 0,
                'delivered' => 0,
                'bounced' => 0,
                'complained' => 0,
                'opens_unique' => 0,
                'opens_total' => 0,
                'clicks_unique' => 0,
                'clicks_total' => 0,
                'device_breakdown' => '{"mobile":0,"desktop":0}',
                'geo_breakdown' => '{}',
                'hourly_open_heatmap' => '[]'
            ];
        }

        // Recent activity
        $recent_logs = $logModel->where('campaign_id', $campaign_id)
            ->where('opened_at IS NOT NULL', null, false)
            ->orderBy('last_opened_at', 'DESC')
            ->limit(10)
            ->find();

        $data = [
            'title' => 'Campaign Analytics: ' . $campaign->title,
            'campaign' => $campaign,
            'stats' => $stats,
            'recent_logs' => $recent_logs
        ];

        return view('admin/newsletters/analytics', $data);
    }
}
